spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/changelog/init.xml

rapid:
  host: https://weatherapi-com.p.rapidapi.com/forecast.json?q={city}
  connect-timeout: 60000
  read-timeout: 60000
  key: 12d1152610msh95c8de17e9a05d3p1e0115jsn442091e9ec04
  fix-rate: 15000
  request:
    city: Minsk
